# Generated by Django 3.2.7 on 2021-09-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FillNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_1', models.IntegerField()),
                ('number_2', models.IntegerField()),
                ('number_3', models.IntegerField()),
                ('text_4', models.CharField(max_length=10)),
            ],
        ),
    ]
