# Generated by Django 3.2.7 on 2021-09-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoderHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.CharField(max_length=20)),
                ('tester', models.CharField(max_length=20)),
                ('infra_dev', models.IntegerField()),
            ],
        ),
    ]
